spring.application.name=SESDemo
server.port=8080

aws.region=eu-central-1
aws.access-key=${AWS_ACCESS_KEY}
aws.secret-key=${AWS_SECRET_KEY}

aws.ses.from-email=Spring Boot SES <mail@ograh.xyz>

resend.api-key=${re_NHQm2G6W_HaJURMBohDRHNQ8zeXfdAW2D}